services:
  doc-studios:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: doc-studios
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
    restart: unless-stopped
